### ISSUE TITLE
Revisa este script para ver com oes algo basico para la carga de imagenes

### ISSUE THREAD

**Issue by abyakko** [moonhuntercode/portfolio-2024-wc#1]
<script>
    function verificarCargaDeImagenes(callback) {
      const images = document.querySelectorAll("img");
      let loadedImages = 0;

      images.forEach((img) => {
        if (img.complete) {
          loadedImages++;
        } else {
          img.addEventListener("load", () => {
            loadedImages++;
            if (loadedImages === images.length) {
              callback();
            }
          });
          img.addEventListener("error", () => {
            loadedImages++;
            if (loadedImages === images.length) {
              callback();
            }
          });
        }
      });

      if (loadedImages === images.length) {
        callback();
      }
    }

    verificarCargaDeImagenes(() => {
      document.getElementById("loading").style.display = "none";
      document.getElementById("content").style.display = "block";
    });
  </script>

**Comment by moonhuntercode** [comment]
tomado en cuenta, y mejorado exitosamente 😎✅, muchas gracias por tu colaboración :✨🚀
